### ISSUE TITLE
unzip not overwriting files

### ISSUE THREAD

**Issue by netzkollektiv** [dnhsoft/shopware-tools#1]
This script cannot really update Shopware as it does not overwrite the existing files. Therefore the files stay as in the current version. The database upgrade leads to errors. See _unzip_ docs:

`unzip -n -q shop-update.zip`

> modifiers:
>  -n  never overwrite existing files

**Comment by chudomir-delchev-dnh** [comment]
I apologize for the late reply. 
I agree this is a bug.

However, we used the script only to upgrade the database and then immediately changed the docker image version. So we were not interested in actually updating the files.

However, I agree this could lead to database errors too, though we never experienced one.

Fixing will come shortly.

**Comment by chudomir-delchev-dnh** [comment]
Flag is removed.
